# Generated by Django 5.2.10 on 2026-04-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='day',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
