# Generated by Django 5.2.10 on 2026-04-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weekday_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'verbose_name': 'Día', 'verbose_name_plural': 'Días'},
        ),
    ]
