# Generated by Django 5.2.10 on 2026-04-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
    ]
