# Generated by Django 5.2.10 on 2026-04-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['time'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
    ]
