# Generated by Django 5.2.10 on 2026-01-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook", "0004_alter_facebookpost_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookgroup",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="groups_screenshots"
            ),
        ),
    ]
