# Generated by Django 5.2.10 on 2026-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_facebookpost_distribution_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('system_prompt', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
