# Generated by Django 5.2.10 on 2026-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0011_agentsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
