# Generated by Django 5.2.10 on 2026-03-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_agentsconfig_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLeadExplorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_explorers', to='facebook.facebookgroupcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_explorers', to='facebook.facebookprofile')),
            ],
        ),
    ]
