# Generated by Django 5.2.10 on 2026-03-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0013_facebookleadexplorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='facebook.facebookprofile'),
        ),
    ]
