# Generated by Django 5.2.10 on 2026-03-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_facebookpost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroup',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='facebook.facebookprofile'),
        ),
    ]
