# Generated by Django 5.2.10 on 2026-03-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_facebookgroup_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroupcategory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_categories', to='facebook.facebookprofile'),
        ),
    ]
