# Generated by Django 5.2.10 on 2026-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0016_facebookgroupcategory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookleadexplorer',
            name='leads_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookleadexplorer',
            name='limit',
            field=models.IntegerField(default=100),
        ),
    ]
