# Generated by Django 5.2.10 on 2026-03-16 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0017_facebookleadexplorer_leads_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='frequency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
