# Generated by Django 5.2.10 on 2026-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0018_facebookpost_frequency_facebookpost_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='frequency',
            field=models.DecimalField(choices=[(2, 'Publicar cada 2h'), (4, 'Publicar cada 4h'), (8, 'Publicar cada 8h')], decimal_places=2, default=0, max_digits=4),
        ),
    ]
