# Generated by Django 5.2.10 on 2026-03-16 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0019_alter_facebookpost_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.ImageField(blank=True, null=True, upload_to='facebook_histories')),
                ('active', models.BooleanField(default=True)),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('published_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='facebook.facebookprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='AgentsConfig',
        ),
    ]
