# Generated by Django 5.2.10 on 2026-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0020_facebookhistory_delete_agentsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookhistory',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
