# Generated by Django 5.2.10 on 2026-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0021_facebookhistory_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='frequency',
            field=models.IntegerField(choices=[(2, 'Publicar cada 2h'), (4, 'Publicar cada 4h'), (8, 'Publicar cada 8h')], default=0),
        ),
    ]
