# Generated by Django 5.2.10 on 2026-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0022_alter_facebookpost_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookgroupcategory',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='categories', to='facebook.facebookgroup'),
        ),
    ]
