# Generated by Django 5.2.10 on 2026-03-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0023_facebookpost_hashtags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpost',
            old_name='title',
            new_name='name',
        ),
    ]
