# Generated by Django 5.2.10 on 2026-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0024_rename_title_facebookpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
