# Generated by Django 5.2.10 on 2026-03-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0025_facebookpost_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookPost',
            new_name='FacebookPostCampaign',
        ),
    ]
