# Generated by Django 5.2.10 on 2026-03-31 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0026_rename_facebookpost_facebookpostcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpostcampaign',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='facebook.facebookgroupcategory'),
        ),
        migrations.AlterField(
            model_name='facebookpostcampaign',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='facebook.facebookprofile'),
        ),
        migrations.AlterField(
            model_name='facebookpostcampaign',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FacebookScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='facebook_post')),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='facebook.facebookprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
