# Generated by Django 5.2.10 on 2026-04-01 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media'),
        ('facebook', '0027_alter_facebookpostcampaign_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookgroup',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='facebookgroupcategory',
            options={'verbose_name': 'Tipo de Grupo', 'verbose_name_plural': 'Tipos de Grupos'},
        ),
        migrations.AlterModelOptions(
            name='facebookhistory',
            options={'verbose_name': 'Historia', 'verbose_name_plural': 'Historias'},
        ),
        migrations.AlterModelOptions(
            name='facebookleadexplorer',
            options={'verbose_name': 'Agente Comercial', 'verbose_name_plural': 'Agentes Comerciales'},
        ),
        migrations.AlterModelOptions(
            name='facebookpostcampaign',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='facebookprofile',
            options={'verbose_name': 'Cuentas', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='facebookscheduledpost',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='facebookhistory',
            name='publish_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookhistory',
            name='weekdays',
            field=models.ManyToManyField(related_name='facebook_histories', to='core.weekday'),
        ),
        migrations.AddField(
            model_name='facebookscheduledpost',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
