# Generated by Django 5.2.10 on 2026-04-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0028_alter_facebookgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='leads_explorer_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
