# Generated by Django 5.2.10 on 2026-04-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0029_facebookprofile_leads_explorer_prompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookgroupcategory',
            options={'verbose_name': 'Lista de Distribución', 'verbose_name_plural': 'Listas de Distribución'},
        ),
    ]
