# Generated by Django 5.2.10 on 2026-04-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0030_alter_facebookgroupcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookleadexplorer',
            name='search_keyword',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='facebookleadexplorer',
            name='group_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_explorers', to='facebook.facebookgroupcategory'),
        ),
    ]
