# Generated by Django 5.2.10 on 2026-04-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0031_facebookleadexplorer_search_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookprofile',
            name='leads_explorer_prompt',
        ),
    ]
