# Generated by Django 5.2.10 on 2026-04-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0032_remove_facebookprofile_leads_explorer_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookleadexplorer',
            old_name='description',
            new_name='agent_description',
        ),
        migrations.AddField(
            model_name='facebookleadexplorer',
            name='agent_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookleadexplorer',
            name='classificator_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
