# Generated by Django 5.2.10 on 2026-04-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0033_rename_description_facebookleadexplorer_agent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookleadexplorer',
            name='group_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_explorers', to='facebook.facebookgroupcategory'),
        ),
    ]
