# Generated by Django 5.2.10 on 2026-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0034_alter_facebookleadexplorer_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='can_post_in_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='can_search_leads',
            field=models.BooleanField(default=False),
        ),
    ]
