# Generated by Django 5.2.10 on 2026-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0035_facebookprofile_can_post_in_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookleadexplorer',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
