# Generated by Django 5.2.10 on 2026-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0036_facebookleadexplorer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookleadexplorer',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
