# Generated by Django 5.2.10 on 2026-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0037_alter_facebookleadexplorer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpostcampaign',
            old_name='categories',
            new_name='distribution_lists',
        ),
    ]
