# Generated by Django 5.2.10 on 2026-04-27 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0038_rename_categories_facebookpostcampaign_distribution_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpostcampaign',
            name='distribution_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='facebookpostcampaign',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
