# Generated by Django 5.2.10 on 2026-04-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0039_alter_facebookpostcampaign_distribution_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpostcampaign',
            options={'ordering': ['created_at'], 'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
    ]
