# Generated by Django 5.2.10 on 2026-04-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0040_alter_facebookpostcampaign_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookleadexplorer',
            old_name='group_category',
            new_name='distribution_list',
        ),
    ]
