# Generated by Django 5.2.10 on 2026-04-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0041_rename_group_category_facebookleadexplorer_distribution_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookLeadExplorer',
            new_name='FacebookAgent',
        ),
    ]
