# Generated by Django 5.2.10 on 2026-04-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0042_rename_facebookleadexplorer_facebookagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookagent',
            name='distribution_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='facebook.facebookgroupcategory'),
        ),
        migrations.AlterField(
            model_name='facebookagent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='facebook.facebookprofile'),
        ),
    ]
