# Generated by Django 5.2.10 on 2026-04-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0043_alter_facebookagent_distribution_list_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookGroupCategory',
            new_name='FacebookDistributionList',
        ),
    ]
