# Generated by Django 5.2.10 on 2026-04-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0044_rename_facebookgroupcategory_facebookdistributionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookdistributionlist',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='distribution_lists', to='facebook.facebookgroup'),
        ),
        migrations.AlterField(
            model_name='facebookdistributionlist',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lists', to='facebook.facebookprofile'),
        ),
    ]
