# Generated by Django 5.2.10 on 2026-04-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0045_alter_facebookdistributionlist_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookdistributionlist',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lists', to='facebook.facebookprofile'),
            preserve_default=False,
        ),
    ]
