# Generated by Django 5.2.10 on 2026-04-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schedule_options'),
        ('facebook', '0047_alter_facebookprofile_managers_facebookagent_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookhistory',
            name='publish_at',
        ),
        migrations.RemoveField(
            model_name='facebookpostcampaign',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='facebookscheduledpost',
            name='publish_at',
        ),
        migrations.AddField(
            model_name='facebookhistory',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schedule'),
        ),
        migrations.AddField(
            model_name='facebookpostcampaign',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.schedule'),
        ),
    ]
