# Generated by Django 5.2.10 on 2026-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0048_remove_facebookhistory_publish_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookagent',
            name='limit',
            field=models.IntegerField(default=10),
        ),
    ]
