# Generated by Django 5.2.10 on 2026-04-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0049_alter_facebookagent_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookdistributionlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
