# Generated by Django 5.2.10 on 2026-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0051_facebookfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookRealAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='facebookprofile',
            name='context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
