# Generated by Django 5.2.10 on 2026-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0052_facebookrealaccount_alter_facebookprofile_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookrealaccount',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
