# Generated by Django 5.2.10 on 2026-05-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0053_facebookrealaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookGroupAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_posts', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.facebookrealaccount')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.facebookgroup')),
            ],
        ),
    ]
