# Generated by Django 5.2.10 on 2026-05-03 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0054_facebookgroupaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgroup',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='facebook.facebookprofile'),
        ),
        migrations.CreateModel(
            name='FacebookProfileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.facebookgroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_groups', to='facebook.facebookprofile')),
            ],
        ),
    ]
