# Generated by Django 5.2.10 on 2026-05-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0055_alter_facebookgroup_profile_facebookprofilegroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookGroupAccount',
            new_name='FacebookAccountGroup',
        ),
    ]
