# Generated by Django 5.2.10 on 2026-05-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0056_rename_facebookgroupaccount_facebookaccountgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccountgroup',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='facebook.facebookrealaccount'),
        ),
        migrations.AlterField(
            model_name='facebookaccountgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_accounts', to='facebook.facebookgroup'),
        ),
    ]
