# Generated by Django 5.2.10 on 2026-05-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0057_alter_facebookaccountgroup_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookprofilegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='facebook.facebookgroup'),
        ),
    ]
