# Generated by Django 5.2.10 on 2026-05-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0058_alter_facebookprofilegroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='real_accounts',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='facebook.facebookrealaccount'),
        ),
    ]
