# Generated by Django 5.2.10 on 2026-05-04 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0059_facebookprofile_real_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookgroup',
            name='profile',
        ),
        migrations.AlterField(
            model_name='facebookprofilegroup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='facebook.facebookprofile'),
        ),
    ]
