# Generated by Django 5.2.10 on 2026-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0060_remove_facebookgroup_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookrealaccount',
            options={'verbose_name': 'Cuenta Real', 'verbose_name_plural': 'Cuentas Reales'},
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='error_at',
        ),
        migrations.RemoveField(
            model_name='facebookgroup',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='facebookprofile',
            name='context',
        ),
        migrations.AddField(
            model_name='facebookaccountgroup',
            name='error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookaccountgroup',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='groups_screenshots'),
        ),
    ]
