# Generated by Django 5.2.10 on 2026-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0061_alter_facebookrealaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccountgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
