# Generated by Django 5.2.10 on 2026-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0062_facebookaccountgroup_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookrealaccount',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='real_profile_screenshots'),
        ),
        migrations.AddField(
            model_name='facebookrealaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
