# Generated by Django 5.2.10 on 2026-05-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0063_facebookrealaccount_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookaccountgroup',
            options={'ordering': ['updated_at']},
        ),
    ]
