# Generated by Django 5.2.10 on 2026-05-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0064_alter_facebookaccountgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookaccountgroup',
            options={'ordering': ['-updated_at']},
        ),
    ]
