# Generated by Django 5.2.10 on 2026-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0065_alter_facebookaccountgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookrealaccount',
            name='can_like_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookrealaccount',
            name='can_see_reels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facebookrealaccount',
            name='can_share_posts',
            field=models.BooleanField(default=False),
        ),
    ]
