# Generated by Django 5.2.10 on 2026-01-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookpost",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts", to="marketing.facebookgroupcategory"
            ),
        ),
    ]
