# Generated by Django 5.2.10 on 2026-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_facebookpost_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="title",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
