# Generated by Django 5.2.10 on 2026-01-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_facebookpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookpost",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="facebook_post"),
        ),
    ]
