# Generated by Django 5.2.10 on 2026-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_facebookgroup_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookprofile",
            name="state_file",
            field=models.FileField(blank=True, null=True, upload_to="profile_states"),
        ),
    ]
