# Generated by Django 5.2.10 on 2026-01-29 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_facebookprofile_state_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="published_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
