# Generated by Django 5.2.10 on 2026-02-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_facebookpost_created_at_facebookpost_published_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroup',
            name='error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
