# Generated by Django 5.2.10 on 2026-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_facebookgroup_error_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookprofile',
            name='state_file',
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
