# Generated by Django 5.2.10 on 2026-02-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_remove_facebookprofile_state_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='distribution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='posts_footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
