"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DEBUG=(bool, False)
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@!x4c09e0*99*v_)w*8_w*1dwg-dhi2bet^6qii$5*l9%24jnp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', cast=bool, default=True)

ALLOWED_HOSTS = ['*']
APPEND_SLASH = True
CORS_ORIGIN_ALLOW_ALL = True
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# CSRF_TRUSTED_ORIGINS = ['https://automations.soluciones-mecanicas.duckdns.org']

# Application definition


INSTALLED_APPS = [
    "daphne",
    "django_q",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_bootstrap5',
    "rest_framework",
    "rest_framework.authtoken",
    "django_jsonform",
    "core",
    "facebook",
    "whatsapp",
    "ia_assistant"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'crum.CurrentRequestUserMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.system_modules"
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": (
        {
            "ENGINE": "django.db.backends.mysql",
            "HOST": env("DATABASE_HOST"),
            "PORT": env("DATABASE_PORT"),
            "NAME": env("DATABASE_NAME"),
            "USER": env("DATABASE_USER"),
            "PASSWORD": env("DATABASE_PASSWORD"),
            "ATOMIC_REQUEST": True,
            "POOL_OPTIONS": {
                "POOL_SIZE": 10,  # Número máximo de conexiones en el pool
                "MAX_OVERFLOW": 20,  # Máximo número de conexiones que pueden ser creadas beyond POOL_SIZE
                "RECYCLE": 1800,  # Tiempo en segundos después del cual una conexión es reciclada
                "PRE_PING": True,  # Verificar si la conexión está activa antes de usarla
                "ECHO": False,  # Mostrar logs de SQL (útil para debugging)
                "TIMEOUT": 30,  # Tiempo máximo de espera para obtener una conexión
            },
        }
        if env("DATABASE_HOST", default=None)
        else {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "ATOMIC_REQUEST": True,
        }
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Havana"
USE_I18N = True
# USE_TZ = True

LOGIN_REDIRECT_URL = reverse_lazy('index')
LOGIN_URL = reverse_lazy('authentication.login')
LOGOUT_REDIRECT_URL = reverse_lazy('authentication.login')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_ROOT = BASE_DIR / "storage/"
MEDIA_URL = "/storage/"
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles/"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "UPLOADED_FILES_USE_URL": True,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAdminUser"],
    # "DATETIME_FORMAT": "%Y-%m-%d %H:%M",
    # "TIME_FORMAT": "%H:%M",
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

BOOTSTRAP5 = {
    # "field_renderers": "core.forms.renderes.ExtraFieldRenderer"
}

PLAYWRIGHT = dict(
    headless=env('PW_HEADLESS', cast=bool, default=True),
    slow_mo=500,
    timeout=150_000
)

Q_CLUSTER = {
    "label": "Tareas pendientes",
    "name": "default",
    "workers": 3,
    "timeout": 50 * 60,
    "recycle": 50,
    "retry": 60 * 60,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "ALT_CLUSTERS": {
        "high_priority": {
            "workers": 1,
            'max_attempts': 3
        },
        "whatsapp": {
            "workers": 1,
            'max_attempts': 1
        },
    },
}

# WAHA_SERVER_URL = 'https://whatsapp.pavelcode5426.duckdns.org'
# WAHA_USERNAME = 'pavelcode5426'
# WAHA_PASSWORD = 'pavelcode5426'
WAHA_SERVER_URL = 'http://waha:3000'
WAHA_USERNAME = None
WAHA_PASSWORD = None
WAHA_APIKEY = 'admin'

IA_OLLAMA_HOST = env("IA_OLLAMA_HOST", default='https://ia.pavelcode5426.duckdns.org')
LLAMAINDEX_TIMEOUT = 1000
LLAMAINDEX_PERSISTENCE_DIR = MEDIA_ROOT / "llama_index"
LLAMAINDEX_CONTEXTSTORE_DIR = LLAMAINDEX_PERSISTENCE_DIR / "contextstore"
CHROMADB_PERSISTENCE_DIR = LLAMAINDEX_PERSISTENCE_DIR / "chromadb"
HUGGINGFACE_TOKEN = env('HUGGINGFACE_TOKEN', default='hf_token')
