# Generated by Django 5.2.10 on 2026-04-01 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False)),
                ('chat_id', models.CharField(editable=False)),
                ('session', models.CharField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(editable=False)),
                ('name', models.CharField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='whatsapp.whatsappaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False)),
                ('chat_id', models.CharField(editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('is_ephemeral', models.BooleanField(default=False, editable=False)),
                ('participant_count', models.IntegerField(editable=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='whatsapp.whatsappaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppDistributionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lists', to='whatsapp.whatsappaccount')),
                ('contacts', models.ManyToManyField(blank=True, related_name='distribution_lists', to='whatsapp.whatsappcontact')),
                ('groups', models.ManyToManyField(blank=True, related_name='distribution_lists', to='whatsapp.whatsappgroup')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')])),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='whatsapp_messages')),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('frequency', models.IntegerField(choices=[(2, 'Publicar cada 2h'), (4, 'Publicar cada 4h'), (8, 'Publicar cada 8h')], default=0)),
                ('publish_at', models.TimeField(blank=True, null=True)),
                ('published_count', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='whatsapp.whatsappaccount')),
                ('distribution_lists', models.ManyToManyField(blank=True, related_name='messages', to='whatsapp.whatsappdistributionlist')),
                ('weekdays', models.ManyToManyField(related_name='whatsapp_messages', to='core.weekday')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('caption', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='whatsapp_status')),
                ('publish_at', models.TimeField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('published_count', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='whatsapp.whatsappaccount')),
                ('weekdays', models.ManyToManyField(related_name='whatsapp_status', to='core.weekday')),
            ],
        ),
    ]
