# Generated by Django 5.2.10 on 2026-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='push_name',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
