# Generated by Django 5.2.10 on 2026-04-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weekday_day'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='weekdays',
            field=models.ManyToManyField(blank=True, related_name='whatsapp_messages', to='core.weekday'),
        ),
        migrations.CreateModel(
            name='WhatsAppLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(editable=False, max_length=250)),
                ('message', models.TextField(editable=False)),
                ('media_url', models.URLField(blank=True, editable=False, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='whatsapp.whatsappaccount')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='whatsapp.whatsappgroup')),
            ],
        ),
    ]
