# Generated by Django 5.2.10 on 2026-04-01 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappcontact_push_name_alter_whatsappcontact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappdistributionlist',
            name='name',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
