# Generated by Django 5.2.10 on 2026-04-03 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_whatsappmessage_weekdays_whatsapplead'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='chat_name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=250),
            preserve_default=False,
        ),
    ]
