# Generated by Django 5.2.10 on 2026-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappdistributionlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='can_use_webhook',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='chat_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='name',
            field=models.CharField(),
        ),
    ]
