# Generated by Django 5.2.10 on 2026-04-04 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsapplead_chat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAutoReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')], default='text', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='whatsapplead',
            options={'verbose_name': 'Posible Cliente', 'verbose_name_plural': 'Posibles Clientes'},
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='publish_at',
        ),
        migrations.RemoveField(
            model_name='whatsappstatus',
            name='caption',
        ),
        migrations.AddField(
            model_name='whatsappstatus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='publish_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
