# Generated by Django 5.2.10 on 2026-04-04 19:35

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappautoreplay_alter_whatsapplead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='auto_replies', to='whatsapp.whatsappaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='button_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='auto_replies'),
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='sections',
            field=django_jsonform.models.fields.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='whatsappautoreplay',
            name='trigger_message',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappautoreplay',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio'), ('list', 'List')], default='text', max_length=10),
        ),
    ]
