# Generated by Django 5.2.10 on 2026-04-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappaccount_can_use_webhook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappaccount',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='whatsappcontact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='whatsappdistributionlist',
            options={'verbose_name': 'Lista de Distribución', 'verbose_name_plural': 'Listas de Distribución'},
        ),
        migrations.AlterModelOptions(
            name='whatsappgroup',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='whatsappstatus',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='name',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
