# Generated by Django 5.2.10 on 2026-04-02 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weekday_day'),
        ('whatsapp', '0005_alter_whatsappaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappstatus',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='text'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')], default='text'),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='file',
            field=models.FileField(blank=True, upload_to='whatsapp_status'),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='publish_at',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='weekdays',
            field=models.ManyToManyField(blank=True, related_name='whatsapp_status', to='core.weekday'),
        ),
    ]
