# Generated by Django 5.2.10 on 2026-04-04 20:35

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappautoreplay_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappautoreplay',
            name='sections',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
