# Generated by Django 5.2.10 on 2026-04-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappstatus_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='chat_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='session',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='chat_id',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='push_name',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappdistributionlist',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='chat_id',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='name',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
