# Generated by Django 5.2.10 on 2026-04-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_alter_whatsappautoreplay_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsAppAutoReplay',
            new_name='WhatsAppAutoReplyMessage',
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='can_auto_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='can_find_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='can_reply_with_ia',
            field=models.BooleanField(default=False),
        ),
    ]
