# Generated by Django 5.2.10 on 2026-04-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_rename_whatsappautoreplay_whatsappautoreplymessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='automatic_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='whatsapp.whatsappautoreplymessage'),
        ),
    ]
