# Generated by Django 5.2.10 on 2026-04-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatsappaccount_automatic_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappautoreplymessage',
            options={'verbose_name': 'Mensaje automático', 'verbose_name_plural': 'Mensajes Automáticos'},
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='agent_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
