# Generated by Django 5.2.10 on 2026-04-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_alter_whatsappautoreplymessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppProcessedLead',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente Procesado',
                'verbose_name_plural': 'Clientes Procesados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatsapp.whatsapplead',),
        ),
    ]
