# Generated by Django 5.2.10 on 2026-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_whatsappprocessedlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='lead_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
