# Generated by Django 5.2.10 on 2026-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_whatsappaccount_lead_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='message_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
