# Generated by Django 5.2.10 on 2026-04-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0014_staticmemory_application'),
        ('whatsapp', '0012_whatsapplead_message_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='agent_prompt',
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='ia_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.ragapplication'),
        ),
    ]
