# Generated by Django 5.2.10 on 2026-04-19 04:22

import dateutil.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_remove_whatsappaccount_agent_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontact',
            name='chat_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='push_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='from_date',
            field=models.DateField(blank=True, default=dateutil.utils.today, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='from_date',
            field=models.DateField(blank=True, default=dateutil.utils.today, null=True),
        ),
    ]
