# Generated by Django 5.2.10 on 2026-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_alter_whatsappcontact_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='whatsapp_profile'),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='can_auto_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='can_use_webhook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='lead_prompt',
            field=models.TextField(blank=True),
        ),
    ]
