# Generated by Django 5.2.10 on 2026-04-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0015_whatsappaccount_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/profile.jpg', null=True, upload_to='whatsapp_profile'),
        ),
    ]
