# Generated by Django 5.2.10 on 2026-04-20 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0016_alter_whatsappaccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='from_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='until_time',
            field=models.TimeField(default=datetime.time(11, 59)),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/profile.jpg', editable=False, null=True, upload_to='whatsapp_profile'),
        ),
    ]
