# Generated by Django 5.2.10 on 2026-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0017_whatsappmessage_from_time_whatsappmessage_until_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Sin intervalo'), (2, 'Publicar cada 2h'), (4, 'Publicar cada 4h'), (8, 'Publicar cada 8h')], default=8),
        ),
    ]
