# Generated by Django 5.2.10 on 2026-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0018_alter_whatsappmessage_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='frequency',
            field=models.IntegerField(choices=[(None, 'Sin intervalo'), (2, 'Publicar cada 2h'), (4, 'Publicar cada 4h'), (8, 'Publicar cada 8h')], default=8, null=True),
        ),
    ]
