# Generated by Django 5.2.10 on 2026-04-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0019_alter_whatsappmessage_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whatsappstatus',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
