# Generated by Django 5.2.10 on 2026-04-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0020_whatsappmessage_order_whatsappstatus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'ordering': ['account', '-order'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
    ]
