# Generated by Django 5.2.10 on 2026-04-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0021_alter_whatsappmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'ordering': ['account', 'order'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='whatsappstatus',
            options={'ordering': ['account', 'order'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
