# Generated by Django 5.2.10 on 2026-04-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0022_alter_whatsappmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappautoreplymessage',
            name='last_whatsapp_id',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='last_whatsapp_id',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whatsappstatus',
            name='last_whatsapp_id',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
