# Generated by Django 5.2.10 on 2026-04-27 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0023_whatsappautoreplymessage_last_whatsapp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='until_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
    ]
