# Generated by Django 5.2.10 on 2026-04-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schedule_options'),
        ('whatsapp', '0024_alter_whatsappmessage_until_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappstatus',
            name='publish_at',
        ),
        migrations.CreateModel(
            name='WhatsAppScheduleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='whatsapp.whatsappmessage')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.schedule')),
            ],
        ),
    ]
