# Generated by Django 5.2.10 on 2026-04-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schedule_options'),
        ('whatsapp', '0025_remove_whatsappstatus_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappstatus',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schedule'),
        ),
        migrations.AlterField(
            model_name='whatsappstatus',
            name='weekdays',
            field=models.ManyToManyField(related_name='whatsapp_status', to='core.weekday'),
        ),
    ]
