# Generated by Django 5.2.10 on 2026-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0028_whatsappcontact_created_by_whatsappcontact_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappautoreplymessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatsappautoreplymessage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='whatsappdistributionlist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatsappdistributionlist',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='whatsappstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whatsappstatus',
            name='updated_by',
        ),
    ]
