# Generated by Django 5.2.10 on 2026-04-30 02:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0030_alter_whatsappaccount_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='whatsappaccount',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
