# Generated by Django 5.2.10 on 2026-04-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0031_alter_whatsappaccount_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='until_time',
        ),
    ]
