# Generated by Django 5.2.10 on 2026-03-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
    ]
