# Generated by Django 5.2.10 on 2026-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0003_agenttool'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
