# Generated by Django 5.2.10 on 2026-03-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0004_agent_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('agents', models.ManyToManyField(related_name='workflows', to='ia_assistant.agent')),
                ('root_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.agent')),
            ],
        ),
    ]
