# Generated by Django 5.2.10 on 2026-03-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0005_agent_options_agentworkflow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentTool',
            new_name='FunctionTool',
        ),
    ]
