# Generated by Django 5.2.10 on 2026-03-07 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0006_rename_agenttool_functiontool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent_workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.agentworkflow')),
            ],
        ),
    ]
