# Generated by Django 5.2.10 on 2026-03-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0007_alter_agent_options_agenttool'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='agentworkflow',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='agent',
            name='llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.ollamallm'),
        ),
        migrations.DeleteModel(
            name='AgentTool',
        ),
    ]
