# Generated by Django 5.2.10 on 2026-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0008_ollamallm_agentworkflow_options_agent_llm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollamallm',
            name='base_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ollamallm',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
