# Generated by Django 5.2.10 on 2026-03-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0008_ollamallm_rename_agent_workflow_agenttool_workflow_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentTool',
        ),
    ]
