# Generated by Django 5.2.10 on 2026-03-09 22:45

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0009_ollamallm_base_url_ollamallm_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='options',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='agentworkflow',
            name='options',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='ollamallm',
            name='config',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
