# Generated by Django 5.2.10 on 2026-03-09 23:09

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0010_alter_agent_options_alter_agentworkflow_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('config', django_jsonform.models.fields.JSONField(verbose_name={'additionalProperties': True, 'keys': {'waha_api_key': {'placeholder': 'admin', 'type': 'string'}, 'waha_base_url': {'placeholder': 'https://whatsapp.com', 'type': 'string'}, 'waha_password': {'placeholder': 'admin', 'type': 'string'}, 'waha_username': {'placeholder': 'admin', 'type': 'string'}}, 'type': 'dict'})),
                ('root_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.agent')),
                ('root_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.agentworkflow')),
            ],
        ),
    ]
