# Generated by Django 5.2.10 on 2026-03-14 16:41

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0011_ragapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('metadata', django_jsonform.models.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='ragapplication',
            name='config',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.CreateModel(
            name='QueryEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_splitter', django_jsonform.models.fields.JSONField()),
                ('extra_kwargs', django_jsonform.models.fields.JSONField()),
                ('documents', models.ManyToManyField(to='ia_assistant.document')),
                ('embed_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embed_queryengine', to='ia_assistant.ollamallm')),
                ('llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llm_queryengine', to='ia_assistant.ollamallm')),
            ],
        ),
    ]
