# Generated by Django 5.2.10 on 2026-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0012_document_alter_ragapplication_config_queryengine'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
