# Generated by Django 5.2.10 on 2026-04-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0013_staticmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmemory',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ia_assistant.ragapplication'),
            preserve_default=False,
        ),
    ]
