# Generated by Django 5.2.10 on 2026-04-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0014_staticmemory_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragapplication',
            name='config',
        ),
    ]
