# Generated by Django 5.2.10 on 2026-04-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_assistant', '0015_remove_ragapplication_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ollamallm',
            name='base_url',
        ),
    ]
